model_name_or_path: /root/autodl-tmp/models/Qwen3-VL-4B-Instruct
adapter_name_or_path: /root/autodl-tmp/saves/dpo
template: qwen3_vl_nothink
trust_remote_code: true

export_dir: /root/autodl-tmp/merged/dpo
export_size: 5
export_device: cpu
export_legacy_format: false